# Generated by Django 3.1 on 2020-08-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passgen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=20)),
                ('length', models.CharField(max_length=2)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
