# Generated by Django 3.0.1 on 2020-08-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passgenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passgen',
            name='length',
            field=models.IntegerField(),
        ),
    ]
