# Generated by Django 3.0.1 on 2020-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passgenapp', '0002_auto_20200807_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='passgen',
            name='password',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
